- hosts: all
  become: yes
  roles:
    - base
    - workstations

 - hosts: all
   become: true
   tasks:
     - name: change user shell to fish 
       become: yes
       user:
         name: marcel
         shell: /bin/fish
