---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for Ubuntu Debian servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
