 - hosts: all
   become: true
   roles:
     - base
    
 - hosts: all
   become: true
   roles:
     - workstations

 - hosts: all
   become: true

  
 - hosts: all
   become: true
   tasks:
     - name: change user shell to fish 
       become: yes
       user:
         name: marcel
         shell: /bin/fish
