---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: lab
  become: true
  tasks:

  - name: install apache and php for Ubuntu Debian servers
    tags: apache2,php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: copy default html file for site
    tags: apache2,html
    copy:
      src: roles/common/files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
