---

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

  - name: create marcel user with home directory
    tags: always
    user:
      name: marcel
      groups: root
      create_home: yes
      home: /home/marcel

  - name: add ssh key for marcel
    tags: always
    authorized_key:
      user: marcel
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEv5IiyjMo2+TC10xpNvDjOukmHtpBfvJMfjZ+AyZVmK ansible"

  - name: add sudoers file for marcel
    tags: always
    copy:
      src: roles/files/sudoer_marcel
      dest: /etc/sudoers.d/marcel
      owner: root
      group: root
      mode: 0440

  - name: add ssh key for marcel
    authorized_key:
      user: marcel
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEv5IiyjMo2+TC10xpNvDjOukmHtpBfvJMfjZ+AyZVmK ansible"
