- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: all
  become: true
  tasks:

  - name: create marcel user
    tags: always
    user:
      name: marcel
      groups: root

  - name: add ssh key for marcel
    tags: always
    authorized_key:
      user: marcel
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEv5IiyjMo2+TC10xpNvDjOukmHtpBfvJMfjZ+AyZVmK ansible"

  - name: add sudoers file for marcel
    tags: always
    copy:
      src: roles/files/sudoer_marcel
      dest: /etc/sudoers.d/marcel
      owner: root
      group: root
      mode: 0440

- name: add ssh key for marcel
   authorized_key:
     user: marcel
     key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEv5IiyjMo2+TC10xpNvDjOukmHtpBfvJMfjZ+AyZVmK ansible"
