---

- name: "install fish shell"
  apt: 
    name: fish
    state: latest
  tags: installation

- name: "Install Common packages (runc, pip, docker io, python3-venv, docker compose, ansible)"
  apt:
    name: ['runc', 'pip', 'docker.io', 'python3-venv', 'docker-compose', 'ansible']
    state: latest
  tags: installation, packages

- name: "Python Docker"
  pip:
    name: 
      - docker
  tags: python

- name: "Install Minikube"
  shell: 
    cmd: curl -Lo ~/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm && chmod +x ~/minikube && mkdir -p /usr/local/bin/ && install ~/minikube /usr/local/bin/
    warn: false
  tags: installation, minikube
  